In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame({"Name":["Jiya","Manali","Gayatri","Suhana","Jiya","Gayatri"] , "English":[89,77,76,81,89,91] , "Hindi":[81,87,77,90,81,77]})

In [16]:
df

      Name  English  Hindi
0     Jiya       89     81
1   Manali       77     87
2  Gayatri       76     77
3   Suhana       81     90
5  Gayatri       91     77

In [15]:
df.drop_duplicates(inplace= True)

In [17]:
df = pd.read_csv("JIYA_MOMIN_dataset(loan_data).csv")

In [18]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [22]:
df.shape

(614, 13)

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
609    False
610    False
611    False
612    False
613    False
Length: 614, dtype: bool

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.shape

(614, 13)