In [1]:
import pandas as pd

In [43]:
df = pd.read_csv("tip.csv")

In [44]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [45]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [47]:
# there are two methods

In [16]:
## method - 1 (get dummys)

In [48]:
df1 = pd.get_dummies(df['sex'])

In [67]:
df1

     Female   Male
0      True  False
1     False   True
2     False   True
3     False   True
4      True  False
..      ...    ...
239   False   True
240    True  False
241   False   True
242   False   True
243    True  False

[244 rows x 2 columns]

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Female  244 non-null    bool
 1   Male    244 non-null    bool
dtypes: bool(2)
memory usage: 620.0 bytes

In [69]:
# method - 2(sikit learn)

In [70]:
from sklearn.preprocessing import OneHotEncoder

In [75]:
var = OneHotEncoder(sparse_output=False)

In [76]:
arr = var.fit_transform(df[['sex']])

In [77]:
pd.DataFrame(arr,columns=["Female","Male"])

     Female  Male
0       1.0   0.0
1       0.0   1.0
2       0.0   1.0
3       0.0   1.0
4       1.0   0.0
..      ...   ...
239     0.0   1.0
240     1.0   0.0
241     0.0   1.0
242     0.0   1.0
243     1.0   0.0

[244 rows x 2 columns]